<?php

/**
 * PluginsfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfGuardUserProfile extends BasesfGuardUserProfile
{
    /**
     * Returns joind firstname and lastname as fullname.
     * @return string
     * @author fizyk
     */
    public function getFullname()
    {
        return trim( $this->getFirstname().' '.$this->getLastname() );
    }

    public function  __toString()
    {
        if( $this->getFirstname() !== null || $this->getLastname() !== null  )
        {
            return $this->getLastname();
        }
        else
        {
            return $this->getUser()->getUsername();
        }
    }
}